# SPDX-FileCopyrightText: Copyright (c) 2026, NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: "tests/data|docs|scripts"

  - repo: https://gitlab.com/pycqa/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        exclude: "tests/data|docs|scripts"
        types:
          - python

  # Remove any leftover legacy HEAVY.AI/OmniSci/MapD header BEFORE verify-copyright
  # runs, so the NVIDIA SPDX header replaces it rather than stacking on top of it.
  - repo: local
    hooks:
      - id: strip-legacy-license-header
        name: strip legacy HEAVY.AI/OmniSci/MapD license headers
        entry: python3 scripts/strip_legacy_license_header.py
        language: system
        files: &license_files |
          (?x)
            [.](py|sh)$

  # Insert/maintain the NVIDIA SPDX header.
  - repo: https://github.com/rapidsai/pre-commit-hooks
    rev: v1.5.0
    hooks:
      - id: verify-copyright
        args: [--fix, --spdx]
        files: *license_files
