repos:
    - repo: https://github.com/psf/black
      rev: 22.3.0
      hooks:
        - id: black
          exclude: "tests/data|docs|benchmarks|scripts|.eggs"

    - repo: https://gitlab.com/pycqa/flake8
      rev: 4.0.1
      hooks:
        - id: flake8
          exclude: "tests/data|docs|benchmarks|scripts|.eggs"
          types:
            - python
