version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.8"

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc

sphinx:
  builder: html
  configuration: docs/source/conf.py
