[build-system]
requires = ["setuptools", "wheel", "pip"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 79
skip-string-normalization = true
target-version = ["py36", "py37", "py38"]
exclude = "tests/data|omnisci|docs|benchmarks|scripts|.eggs"
