{% set name = "heavyai" %}
{% set version = "0.27.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../../..

build:
  number: 0
  noarch: python
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - pip
    - setuptools
    - setuptools_scm
    - git
  run:
    - python
    - numpy
    - pyomniscidb
    - pandas
    - pyarrow <=3.0.0
    - shapely
  
test:
  source_files:
    - tests
  requires:
    - pytest
    - coverage
    - pytest-mock
    - geopandas
  commands:
    - "pytest -sv tests/"

about:
  home: http://github.com/heavyai/heavyai
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.md
  summary: A python DB API 2 compatible client for OmniSci (formerly OmniSci and MapD).
  description: |
    A python DB API 2 compatible client for OmniSci (formerly OmniSci and MapD).
  doc_url: https://heavyai.readthedocs.io
  dev_url: https://github.com/heavyai/heavyai

extra:
  recipe-maintainers:
    - TomAugspurger
    - andrewseidl
    - xhochy
    - xmnlab
    - jclay
    - alexbaden
