name: heavyai-dev
channels:
- conda-forge
- defaults
dependencies:
- pandas
- pyarrow>=3.0.0
- pandas
- python >=3.7.0
- geopandas
- shapely
- numpy
- numpydoc
- coverage
- flake8
- pre-commit
- pytest
- pytest-cov
- pytest-mock
- sphinx
- sphinx_rtd_theme
