name: heavyai-gpu-dev
channels:
- rapidsai
- nvidia
- conda-forge
- defaults
dependencies:
- cudf ==0.18
- cudatoolkit=11.0
- python >=3.7.0
- pyarrow>=3.0.0=*cuda
- thrift >=0.13
- sqlalchemy  # 3.10 issue with one of its dependency if pip
- pandas
- geopandas
- shapely
- numpy
- numpydoc
- coverage
- flake8
- pre-commit
- pytest
- pytest-cov
- pytest-mock
- sphinx
- sphinx_rtd_theme
